spring:
  data:
    redis:
      repositories:
        enabled: false
      database: 0
      connect-timeout: 10s
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
