/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSettings: typeof import('./src/components/settings/AboutSettings.vue')['default']
    AIModelList: typeof import('./src/components/settings/AIModelList.vue')['default']
    AIProviderCard: typeof import('./src/components/settings/AIProviderCard.vue')['default']
    AIProviderConfigForm: typeof import('./src/components/settings/AIProviderConfigForm.vue')['default']
    AIProviderSettings: typeof import('./src/components/settings/AIProviderSettings.vue')['default']
    ChatArea: typeof import('./src/components/chat/ChatArea.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FileContentDialog: typeof import('./src/components/knowledge/FileContentDialog.vue')['default']
    FileList: typeof import('./src/components/knowledge/FileList.vue')['default']
    FileUpload: typeof import('./src/components/knowledge/FileUpload.vue')['default']
    GeneralSettings: typeof import('./src/components/settings/GeneralSettings.vue')['default']
    KnowledgeBaseDetail: typeof import('./src/components/KnowledgeBaseDetail.vue')['default']
    KnowledgeBaseDialog: typeof import('./src/components/KnowledgeBaseDialog.vue')['default']
    KnowledgeBaseHome: typeof import('./src/components/KnowledgeBaseHome.vue')['default']
    KnowledgeBaseSidebar: typeof import('./src/components/KnowledgeBaseSidebar.vue')['default']
    KnowledgeDetail: typeof import('./src/components/knowledge/KnowledgeDetail.vue')['default']
    KnowledgeDialog: typeof import('./src/components/knowledge/KnowledgeDialog.vue')['default']
    KnowledgeHome: typeof import('./src/components/knowledge/KnowledgeHome.vue')['default']
    KnowledgeSidebar: typeof import('./src/components/knowledge/KnowledgeSidebar.vue')['default']
    LoginDialog: typeof import('./src/components/common/LoginDialog.vue')['default']
    MessageBubble: typeof import('./src/components/chat/MessageBubble.vue')['default']
    MessageInput: typeof import('./src/components/chat/MessageInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionList: typeof import('./src/components/chat/SessionList.vue')['default']
    SettingsContent: typeof import('./src/components/settings/SettingsContent.vue')['default']
    SettingsSidebar: typeof import('./src/components/settings/SettingsSidebar.vue')['default']
    SidebarNav: typeof import('./src/components/common/SidebarNav.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
